version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .flaskenv
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      DATABASE_URL: ${DATABASE_URL}
      SCHEMA: ${SCHEMA}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "5000:8000"
    volumes:
      - ./app:/var/www/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  react-vite:
    build:
      context: .
      dockerfile: react-vite/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./react-vite:/var/www/react-vite
