"""added flowchart id to arrow model

Revision ID: 2609899d4b31
Revises: 5f310e0c2a80
Create Date: 2024-03-12 23:02:02.534291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2609899d4b31'
down_revision = '5f310e0c2a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arrows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flowchart_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'flowcharts', ['flowchart_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arrows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('flowchart_id')

    # ### end Alembic commands ###
