"""added to_ and from_ connectors

Revision ID: 5f310e0c2a80
Revises: 041ed425d89a
Create Date: 2024-03-12 00:14:29.053701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f310e0c2a80'
down_revision = '041ed425d89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arrows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_connector', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('to_connector', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arrows', schema=None) as batch_op:
        batch_op.drop_column('to_connector')
        batch_op.drop_column('from_connector')

    # ### end Alembic commands ###
